// ===================================
// DONNÉES D'EXEMPLE — BRVM Academy
// Remplacez par les données de votre API
// ===================================

export const SAMPLE_COURSES = [
  {
    id: '1',
    title: 'Introduction à la BRVM : Comprendre la Bourse Ouest-Africaine',
    description: 'Découvrez le fonctionnement de la BRVM, les marchés actions et obligations, et comment ouvrir votre premier compte titre.',
    category: 'Fondamentaux',
    level: 'debutant',
    duration: '2h 45min',
    videoCount: 12,
    rating: 4.9,
    students: '2.4K',
    emoji: '📈',
    thumbClass: 'bg-gradient-to-br from-[#1a3a2a] to-[#0d1f17]',
    progress: 75,
    completedLessons: 9,
    instructor: 'Ibrahima Ndiaye',
    lessons: [
      { id: 'l1', title: "Qu'est-ce que la BRVM ?", duration: '12:30', videoUrl: '' },
      { id: 'l2', title: 'Les 8 pays de la zone UEMOA', duration: '8:45', videoUrl: '' },
      { id: 'l3', title: 'Actions vs Obligations', duration: '15:20', videoUrl: '' },
      { id: 'l4', title: 'Comment ouvrir un compte titre', duration: '18:00', videoUrl: '' },
      { id: 'l5', title: "Les SGI (Sociétés de Gestion et d'Intermédiation)", duration: '14:10', videoUrl: '' },
      { id: 'l6', title: 'Lire une cotation BRVM', duration: '11:30', videoUrl: '' },
      { id: 'l7', title: 'Les indices BRVM-Composite et BRVM-10', duration: '13:45', videoUrl: '' },
      { id: 'l8', title: 'Passer un ordre au marché', duration: '16:20', videoUrl: '' },
      { id: 'l9', title: 'Passer un ordre à cours limité', duration: '14:50', videoUrl: '' },
      { id: 'l10', title: 'Les frais de courtage', duration: '10:15', videoUrl: '' },
      { id: 'l11', title: 'La fiscalité boursière en zone UEMOA', duration: '17:30', videoUrl: '' },
      { id: 'l12', title: 'Résumé et quiz final', duration: '8:00', videoUrl: '' },
    ],
  },
  {
    id: '2',
    title: 'Analyse Technique des Actions BRVM',
    description: 'Maîtrisez les chandeliers japonais, les supports/résistances et les indicateurs clés pour trader sur la BRVM.',
    category: 'Analyse Technique',
    level: 'intermediaire',
    duration: '3h 20min',
    videoCount: 18,
    rating: 4.8,
    students: '1.8K',
    emoji: '📊',
    thumbClass: 'bg-gradient-to-br from-[#2a1a0a] to-[#1f0d05]',
    progress: 30,
    completedLessons: 5,
    instructor: 'Fatou Diallo',
    lessons: [
      { id: 'l1', title: 'Introduction à l\'analyse technique', duration: '10:00', videoUrl: '' },
      { id: 'l2', title: 'Les chandeliers japonais', duration: '14:30', videoUrl: '' },
      { id: 'l3', title: 'Supports et résistances', duration: '12:00', videoUrl: '' },
    ],
  },
  {
    id: '3',
    title: "Stratégies d'Investissement UEMOA",
    description: 'Construisez un portefeuille diversifié avec les meilleures actions de la zone UEMOA. Dividendes, croissance et valeur.',
    category: 'Stratégies',
    level: 'avance',
    duration: '4h 10min',
    videoCount: 22,
    rating: 4.7,
    students: '1.2K',
    emoji: '💰',
    thumbClass: 'bg-gradient-to-br from-[#0a1a2a] to-[#050d1f]',
    progress: 0,
    completedLessons: 0,
    instructor: 'Moussa Traoré',
    lessons: [],
  },
  {
    id: '4',
    title: 'Investir dans les Obligations BRVM',
    description: "Comprenez le marché obligataire ouest-africain, les emprunts d'État et les obligations d'entreprises cotées.",
    category: 'Obligations',
    level: 'debutant',
    duration: '1h 50min',
    videoCount: 8,
    rating: 4.6,
    students: '980',
    emoji: '🏦',
    thumbClass: 'bg-gradient-to-br from-[#2a0a1a] to-[#1f050d]',
    progress: 0,
    completedLessons: 0,
    instructor: 'Awa Konaté',
    lessons: [],
  },
  {
    id: '5',
    title: 'Lire les États Financiers des Sociétés Cotées',
    description: 'Apprenez à analyser les bilans, comptes de résultat et ratios financiers des entreprises listées à la BRVM.',
    category: 'Analyse Fondamentale',
    level: 'intermediaire',
    duration: '3h 00min',
    videoCount: 15,
    rating: 4.9,
    students: '1.5K',
    emoji: '🔍',
    thumbClass: 'bg-gradient-to-br from-[#1a2a0a] to-[#0d1f05]',
    progress: 0,
    completedLessons: 0,
    instructor: 'Ibrahima Ndiaye',
    lessons: [],
  },
  {
    id: '6',
    title: 'Ouvrir un Compte Titre & Passer ses Premiers Ordres',
    description: 'Guide pas-à-pas pour ouvrir un compte chez un SGI, utiliser la plateforme de trading, et placer vos premiers ordres.',
    category: 'Pratique',
    level: 'debutant',
    duration: '2h 15min',
    videoCount: 10,
    rating: 4.8,
    students: '3.1K',
    emoji: '🌐',
    thumbClass: 'bg-gradient-to-br from-[#0a2a2a] to-[#051f1f]',
    progress: 0,
    completedLessons: 0,
    instructor: 'Fatou Diallo',
    lessons: [],
  },
];

export const SAMPLE_TUTORIALS = [
  {
    id: 't1',
    title: 'Comment utiliser Daba pour acheter des actions BRVM',
    description: "Tutoriel étape par étape pour investir via l'application mobile Daba.",
    readTime: '15 min',
    views: '4.2K',
    icon: '📱',
    color: 'bg-gold/10',
  },
  {
    id: 't2',
    title: 'Calculer le rendement de dividendes sur les actions BRVM',
    description: 'Apprenez à évaluer la rentabilité de vos investissements en dividendes.',
    readTime: '10 min',
    views: '3.1K',
    icon: '📋',
    color: 'bg-emerald/15',
  },
  {
    id: 't3',
    title: 'Construire un portefeuille équilibré avec 500 000 FCFA',
    description: 'Stratégie pratique pour démarrer l\'investissement avec un budget modeste.',
    readTime: '20 min',
    views: '6.8K',
    icon: '📐',
    color: 'bg-blue-500/10',
  },
  {
    id: 't4',
    title: 'Les 10 erreurs à éviter pour un débutant sur la BRVM',
    description: 'Conseils essentiels pour protéger votre capital en tant que nouvel investisseur.',
    readTime: '12 min',
    views: '8.5K',
    icon: '⚡',
    color: 'bg-orange-500/10',
  },
];

export const SAMPLE_MARKET_DATA = [
  { symbol: 'SNTS', name: 'Sonatel', sector: 'Télécoms', price: '14 850', change: '+2.41%', up: true, volume: '45 230' },
  { symbol: 'SGBC', name: 'Société Générale CI', sector: 'Banque', price: '12 500', change: '+1.12%', up: true, volume: '22 100' },
  { symbol: 'TTLC', name: 'Total CI', sector: 'Énergie', price: '2 380', change: '-0.83%', up: false, volume: '18 750' },
  { symbol: 'SOLC', name: 'Solibra CI', sector: 'Industrie', price: '158 000', change: '+0.64%', up: true, volume: '1 250' },
  { symbol: 'ETIT', name: 'Ecobank TI', sector: 'Banque', price: '17', change: '-1.16%', up: false, volume: '890 000' },
  { symbol: 'PALC', name: 'Palm CI', sector: 'Agriculture', price: '5 950', change: '+3.48%', up: true, volume: '8 320' },
];

export const UEMOA_COUNTRIES = [
  { code: 'CI', name: "Côte d'Ivoire", flag: '🇨🇮' },
  { code: 'SN', name: 'Sénégal', flag: '🇸🇳' },
  { code: 'BF', name: 'Burkina Faso', flag: '🇧🇫' },
  { code: 'ML', name: 'Mali', flag: '🇲🇱' },
  { code: 'TG', name: 'Togo', flag: '🇹🇬' },
  { code: 'BJ', name: 'Bénin', flag: '🇧🇯' },
  { code: 'NE', name: 'Niger', flag: '🇳🇪' },
  { code: 'GW', name: 'Guinée-Bissau', flag: '🇬🇼' },
];
